---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    quay-enterprise-component: clair-scanner
  name: clair-scanner
  namespace: {{ PROJECT_NAME }}
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-enterprise-component: clair-scanner
  template:
    metadata:
      labels:
        quay-enterprise-component: clair-scanner
      namespace: {{ PROJECT_NAME }}
    spec:
      containers:
      - image: {{ CLAIR_IMAGE }}
        imagePullPolicy: IfNotPresent
        name: clair-scanner
        ports:
        - containerPort: 6060
          name: clair-api
          protocol: TCP
        - containerPort: 6061
          name: clair-health
          protocol: TCP
        volumeMounts:
        - mountPath: /clair/config
          name: configvolume
          readOnly: true
        - mountPath: /etc/pki/ca-trust/source/anchors/ca.crt
          name: clair-trust-ca-secret
          subPath: ca.crt
          readOnly: true
      imagePullSecrets:
      - name: {{ PULL_SECRET_NAME }}
      restartPolicy: Always
      volumes:
      - name: configvolume
        secret:
          secretName: {{ CLAIR_SCANNER_SECRET }}
          defaultMode: 420
      - name: clair-trust-ca-secret
        secret:
          secretName: clair-trust-ca-secret
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: {{ CLAIR_SVC }} 
  namespace: {{ PROJECT_NAME }} 
spec:
  ports:
  - name: clair-api
    port: 6060
    protocol: TCP
    targetPort: 6060
  - name: clair-health
    port: 6061
    protocol: TCP
    targetPort: 6061
  selector:
    quay-enterprise-component: clair-scanner
  type: ClusterIP
